//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressiveTouchStudy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImpactForce:Hard,Normal,Soft;VelocityTouchUp:Fast,Normal,Slow;DirectionOfApproach" +
            ":Above,Below,Left,Right;FingerAngle:High,Normal,Flat;TwistingTouch:Default;Quive" +
            "ringFinger:Default;")]
        public string InteractionTechniques {
            get {
                return ((string)(this["InteractionTechniques"]));
            }
            set {
                this["InteractionTechniques"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TrialsPerCondition {
            get {
                return ((int)(this["TrialsPerCondition"]));
            }
            set {
                this["TrialsPerCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TwistingTouch:Default;")]
        public string InteractionTechniques_Debug {
            get {
                return ((string)(this["InteractionTechniques_Debug"]));
            }
            set {
                this["InteractionTechniques_Debug"] = value;
            }
        }
    }
}
